### ISSUE TITLE
Add --no-cache-dir option in pip install

### ISSUE THREAD

**Issue by fredj** [Oslandia/docker-mapproxy#1]
To save an extra bit of disk space, `--no-cache-dir` option could be added to the `pip3 install` command in the Dockerfile.

See https://pip.pypa.io/en/stable/reference/pip_install/#caching

**Comment by elemoine** [comment]
Sounds good. I'll add that.

**Comment by elemoine** [comment]
Changed with https://github.com/Oslandia/docker-mapproxy/pull/2.
